### ISSUE TITLE
Issues I’m having with understanding what I need to know to make a hand-held music player

### ISSUE THREAD

**Issue by V1V0TheCalico** [V1V0TheCalico/Music-Player-Beetle#1]
Alright so I’m trying to make this hand held music player FROM SCRATCH (not the coding website). And that means figuring out the code and circuitry for this thing, but I’m mainly here to ask what I need to know to code this thing because I’m getting frustrated and don’t know where else to turn to with this.

Here’s a basic run down of what I want this thing to do over all:

* I want it to be able to play music WITHOUT internet, so the music will be downloaded onto the device
* I want it to have the option to play with and without Blue Tooth (wanting the device to have speakers, plus some kind of volume control)
* I’m also wanting it to have a little display screen to show what song is playing and show the different Artists and playlists to choose from (it wont be touch screen)
* Buttons to control the “cursor” on the screen (similar to buttons on the Nintendo DS)

Here are the things I’m having trouble figuring out for the code as of current:

* what programming language is recommended for this kind of project? I’ve been trying to use HTML and CSS, along with trying to learn Javascript.
* how would I set up a folder of downloaded music and getting the device to play the music from said folder?
* What file type is recommended for downloading music for a project like this?
* I want it to also be able to shuffle/ randomize what song comes next

If you can’t answer all of my questions that’s fine, just answer as many/ or whatever you do know I’m dying to know just ANYTHING to figure this stuff out 😭. And if you have any questions for me or if something isn’t clear I will answer you as soon as I can.

**Comment by FurqanHun** [comment]
I'm not an expert on hardware level programming but i'd try to answer some of your questions.

> **Q. what programming language is recommended for this kind of project? I’ve been trying to use HTML and CSS, along with trying to learn Javascript.**

The choice of programming language often depends on the hardware you're using. Different microcontrollers or single-board computers have varying levels of compatibility with programming languages.

for example if you're using an Arduino microcontroller, the primary language for programming it is C/C++. On the other hand, if you're using a Raspberry Pi, you have more flexibility and can use languages like Python, C/C++, or even others like JavaScript.

you might want to consider the following while deciding the programming language:
1. Hardware Compatibility (ensuring that the hardware supports the language you choose which can be checked on their documentations)

2. Library support (you might want to check if the language has libraries or APIs that can help you achieve the functionality you need for your project)

3. Community Support (consider the size and activity of the community around the language)

4. And most importantly, check if you're comfortable at using the language.

_also i don't think htmls, css are recommended languages to use for this task_

> **Q. how would I set up a folder of downloaded music and getting the device to play the music from said folder?**

I don't know which language you'll end up choosing so from now on I'll use python to demonstrate examples as i learned it recently (at beginner - inter level)

In Python, you can use the os module to create a directory:
``` python
import os
os.mkdir("music_folder")
```
 you can also use the os module to list the files in the music folder:
 ```python
 import os
music_files = os.listdir("music_folder")
```
You can use the **pygame** library for audio playback. Use the appropriate functions from your audio playback library to control the playback.

> **Q. What file type is recommended for downloading music for a project like this?**

The file type depends on what you're looking for, most of the devices or programs go for MP3 due to its compression. other options could be WAV or FLAC.

here's a difference between each of them:
1. **MP3** is a popular choice for its balance of audio quality and file size, making it suitable for portable devices with limited storage capacity.

2. **WAV** files offer higher audio quality but come with larger file sizes

3.  **FLAC (Free Lossless Audio Codec)** provides high-quality audio with compression that retains the original audio data

> **Q. I want it to also be able to shuffle/ randomize what song comes next**

Here's a python script i just wrote to play music in shuffled order (the files i've in **Tatsuro Yamashita - Cosy** folder are in FLAC btw).

```python
import os
import random
import pygame
import keyboard

# Initializing pygame
pygame.init()

# music foler path
music_folder = "Tatsuro Yamashita - Cosy"

# getting the list of music files
music_files = os.listdir(music_folder)

# shuffling the playlist
random.shuffle(music_files)

# would play in shuffled orfer
for music_file in music_files:
    pygame.mixer.music.load(os.path.join(music_folder, music_file))
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        if keyboard.is_pressed('shift+q'): # Press shift + q to stop the music (didn't wanted to close the terminal manually)
            pygame.mixer.music.stop()
            break
        pygame.time.Clock().tick(10)  # Only adjust as needed for smoother playback
```

I'd recommend you checking out resources on which micro-controller would be more suitable for your project and needs and then choosing a language that is most suitable for that micro-controller and your needs, also check out resouces on audio electrnoics related to your project like amplifier and stuff.

here are some resouces to start:
1. [All About Circuits - An Introduction to Audio Electronics: Sound, Microphones, Speakers, and Amplifiers](https://www.allaboutcircuits.com/technical-articles/introduction-audio-electronics-sound-microphones-speakers-amplifiers/)
2. [Electronic Tutorials - Introduction to the Amplifier](https://www.electronics-tutorials.ws/amplifier/amp_1.html)

You can also use sites like [hackday](https://hackaday.com/) or [YouTube](https://www.youtube.com) or even github repos to check other similar projects.

_If you have any more questions or need help with somehting feel free to ask._

**Comment by V1V0TheCalico** [comment]
I am new to this app but thank you so much for all of this info man you are a LIFE SAVER 😭🙏

**Comment by FurqanHun** [comment]
> I am new to this app but thank you so much for all of this info man you are a LIFE SAVER 😭🙏

No worries, glad I could help. If you have any more questions or need assistance with anything else feel free to ask I'd try my best to help you.
